version: '2'

services:
# BASE DE DADOS MySQL 
    percona:
        image: percona
        restart: always
        container_name: orange_percona
        volumes:
            - ./data/percona:/var/lib/mysql
            - ./dumps:/dumps
        ports:
            - "3306:3306"
        environment:
          MYSQL_USERNAME: root
          MYSQL_ROOT_PASSWORD: root
        networks:
            - network-back
